# Generated by Django 6.0.4 on 2026-05-20 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Frigorifico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ingredientes", models.ManyToManyField(to="idjango.ingrediente")),
            ],
        ),
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        default="defaultProfile.png", upload_to="profile_pics"
                    ),
                ),
                ("bio", models.TextField(null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("User", "User"),
                            ("Guest", "Guest"),
                            ("EventOrganizer", "EventOrganizer"),
                        ],
                        default="User",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frigorifico",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="idjango.frigorifico",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "foto",
                    models.ImageField(
                        default="defaultRecipe.png", upload_to="recipe_pics"
                    ),
                ),
                ("instrucao", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("ingredientes", models.ManyToManyField(to="idjango.ingrediente")),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criador_receita",
                        to="idjango.utilizador",
                    ),
                ),
                (
                    "guardadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="receitas_guardadas",
                        to="idjango.utilizador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "foto",
                    models.ImageField(
                        default="defaultEvent.png", upload_to="Event_pics"
                    ),
                ),
                ("horario", models.JSONField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("data_evento", models.DateTimeField()),
                ("descricao", models.TextField()),
                (
                    "capacidade_max",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(5)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_criados",
                        to="idjango.utilizador",
                    ),
                ),
                (
                    "inscritos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eventos_inscritos",
                        to="idjango.utilizador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "receita",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="idjango.receita",
                    ),
                ),
                (
                    "utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="idjango.utilizador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="idjango.receita",
                    ),
                ),
                (
                    "utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="idjango.utilizador",
                    ),
                ),
            ],
        ),
    ]
