# Generated by Django 6.0.4 on 2026-05-15 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidade_max',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='classificacao',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='guardadores',
            field=models.ManyToManyField(blank=True, related_name='receitas_guardadas', to='idjango.utilizador'),
        ),
    ]
