# Generated by Django 4.2.11 on 2026-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='eventos_inscritos', to='idjango.utilizador'),
        ),
    ]
