# Generated by Django 4.2.11 on 2026-05-17 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='classificacao',
        ),
        migrations.AlterField(
            model_name='evento',
            name='capacidade_max',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='guardadores',
            field=models.ManyToManyField(blank=True, related_name='receitas_guardadas', to='idjango.utilizador'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='idjango.receita')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idjango.utilizador')),
            ],
        ),
    ]
