# Generated by Django 6.0.4 on 2026-05-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='frigorifico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='idjango.frigorifico'),
        ),
    ]
