# Generated by Django 6.0.4 on 2026-05-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0002_utilizador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capacidade_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='receita',
            name='classificacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='eventos',
            field=models.ManyToManyField(to='idjango.evento'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='receitas',
            field=models.ManyToManyField(to='idjango.receita'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='frigorifico',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='instrucao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(default='Receita Sem Nome', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='utilizador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idjango.comentario'),
        ),
    ]
