# Generated by Django 6.0.4 on 2026-05-15 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0002_alter_evento_capacidade_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='classificacao',
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='idjango.receita')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idjango.utilizador')),
            ],
            options={
                'unique_together': {('utilizador', 'receita')},
            },
        ),
    ]
