# Generated by Django 6.0.4 on 2026-05-21 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0002_alter_utilizador_frigorifico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='classificacao',
        ),
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
