# Generated by Django 6.0.4 on 2026-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0002_alter_evento_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='guardadores',
            field=models.ManyToManyField(blank=True, related_name='receitas_guardadas', to='idjango.utilizador'),
        ),
    ]
