# Generated by Django 6.0.4 on 2026-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0003_alter_receita_guardadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frigorifico',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='idjango.ingrediente'),
        ),
    ]
