# Generated by Django 6.0.4 on 2026-05-15 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0003_remove_receita_classificacao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='classificacao',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
