# Generated by Django 6.0.4 on 2026-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0003_remove_receita_classificacao_evento_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='cookie_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
