# Generated by Django 6.0.4 on 2026-05-15 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0004_receita_classificacao_delete_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='classificacao',
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='idjango.receita')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idjango.utilizador')),
            ],
        ),
    ]
