# Generated by Django 6.0.4 on 2026-05-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0004_alter_frigorifico_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
