# Generated by Django 6.0.4 on 2026-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idjango", "0005_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilizador",
            name="imagem",
            field=models.ImageField(
                default="defaultProfile.svg", upload_to="profile_pics"
            ),
        ),
    ]
