# Generated by Django 6.0.4 on 2026-05-18 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0005_remove_receita_classificacao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
