# Generated by Django 6.0.4 on 2026-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0006_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
