# Generated by Django 6.0.4 on 2026-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango', '0008_evento_is_active_frigorifico_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='nome',
        ),
    ]
